Added options

diff --git a/lock b/lock
--- a/lock
+++ b/lock
@@ -5,50 +5,68 @@ declare -r password="pass"
 # start of title screen
 clear
 cat title_screen.txt
-echo -n "\n"
 # end of title screen
 
-while : ; do
-	echo -en "\nPassword: "
-	read -s user_password
-	[[ $user_password == $password ]] || echo -en "\n   Error: incorrect password"	
-	[[ $user_password != $password ]] || break	# terminating condition
+while getopts ":evnh" option; do
+    case $option in
+        e) # emacs
+            emacs_flag=1
+            ;;
+        v) # vim
+            vim_flag=1
+            ;;
+        n) # nano
+            nano_flag=1
+            ;;
+        h)
+            help_flag=1
+            ;;
+        *)  # default
+            error_flag=1
+            ;;
+    esac
 done
 
-# allowing user to select text editor of choice
-echo -e "\nSuccess: please select shell text editor of choice (default is Emacs)"
-sleep 0.3
-echo -e "[1] Emacs"
-echo -e "[2] VIM"
-echo -e "[3] Nano"
-echo -n "Input: "
-read user_input_text_editor
-case $user_input_text_editor in
-	1)
-		emacs_flag=1
-		;;
-	2)
-		vim_flag=1
-		;;
-	3) 
-		nano_flag=1
-		;;
-	*)
-		emacs_flag=1
-		;;
-	esac
+# help flag
+if [[ help_flag -eq 1 ]]; then
+    echo -e "\t\nSyntax: lock [-evnh]"
+    echo -e "\toptions:"
+    echo -e "\te            Access sensitive data using Emacs"
+    echo -e "\tv            Access sensitive data using Vim"
+    echo -e "\tn            Access sensitive data using Nano"
+    echo -e "\th            Show help page"
+    continue=0  # assign variable, continue, to false
+fi
 
-# success page
-echo -ne "\nOpening sensitive data using "
+while : ; do
+    echo -en "\n\nPassword: "
+    read -s user_password
+    [[ $user_password == $password ]] || echo -en "\n   Error: incorrect password"  
+    [[ $user_password != $password ]] || break  # terminating condition
+done
+
+# emacs flag set
 if [[ emacs_flag -eq 1 ]]; then
-	echo "Emacs"
-elif [[ vim_flag -eq 1 ]]; then
-	echo "Vim"
-elif [[ nano_flag -eq 1 ]]; then
-	echo "Nano"
+    echo -ne "\nOpening sensitive data using Emacs"
+fi
+
+# vim flag set
+if [[ vim_flag -eq 1 ]]; then
+    echo -ne "\nOpening sensitive data using Vim"
+fi
+
+# nano flag set
+if [[ nano_flag -eq 1 ]]; then
+    echo -ne "\nOpening sensitive data using Nano"
+fi
+
+# error flag set
+if [[ error_flag -eq 1 ]]; then
+    echo -ne "\nError: invalid option, refer to help page"
 fi
 
 # opening with text editor of choice
+echo -ne "\n"
 echo -ne '[######...................]   33%  \r'
 sleep 1
 echo -ne '[##############...........]   66%  \r'
@@ -59,9 +77,9 @@ echo -ne '\n'
 
 # opening with text editor
 if [[ emacs_flag -eq 1 ]]; then
-	emacs data.txt
+    emacs data.txt
 elif [[ vim_flag -eq 1 ]]; then
-	vim data.txt
+    vim data.txt
 elif [[ nano_flag -eq 1 ]]; then
-	nano data.txt
+    nano data.txt
 fi
